name: macOS Build and Test

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행
  pull_request: # Pull Request 생성 시 실행

jobs:
  build:
    runs-on: macos-latest  # 최신 macOS 환경 사용

    steps:
      # 1. 저장소에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Python 및 pip 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # 사용할 Python 버전 지정

      # 3. 필요한 의존성 설치
      - name: Install dependencies
        run: |
          pip install --upgrade pip  # pip 업데이트
          pip install pytesseract pillow opencv-python-headless  # 필요한 패키지 설치

      # 4. 프로그램 빌드
      - name: Build application
        run: |
          python hwahui_hellfire_timer_v4_mac.py  # 빌드 스크립트 실행

      # 5. 테스트 실행
      - name: Run tests
        run: |
          python hwahui_hellfire_timer_v4_mac.py  # 테스트 스크립트 실행
