name: macOS Build and Test

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행
  pull_request: # Pull Request 생성 시 실행

jobs:
  build:
    runs-on: macos-latest  # 최신 macOS 환경 사용

    steps:
      # 1. 저장소에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 필요한 의존성 설치 (예: Python, Homebrew 등)
      - name: Install dependencies
        run: |
          brew install python  # Homebrew로 Python 설치

      # 3. 프로그램 빌드
      - name: Build application
        run: |
          python hwahui_hellfire_timer_v4_mac.py  # 빌드 스크립트 실행

      # 4. 테스트 실행
      - name: Run tests
        run: |
          python hwahui_hellfire_timer_v4_mac.py  # 테스트 스크립트 실행
