name: macOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. 저장소에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 캐시 지우기
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      # 3. Python 설치 (x64 아키텍처 사용)
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1
          architecture: x64

      # 4. 필요한 의존성 설치
      - name: Install dependencies
        run: |
          brew install python  # 필요한 의존성 설치
          brew install tesseract  # pytesseract를 사용하려면 tesseract가 필요
          pip install pynput pyautogui Pillow  # 필요한 Python 패키지 설치
          pip install opencv-python # OpenCV가 필요하면 설치

      # 5. 프로그램 빌드
      - name: Build application
        run: |
          python hwahui_hellfire_timer_v4_mac.py  # 빌드 스크립트 실행

      # 6. 테스트 실행
      - name: Run tests
        run: |
          python hwahui_hellfire_timer_v4_mac.py.py  # 테스트 스크립트 실행
